# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory to /app
WORKDIR src/app

# Copy package.json and package-lock.json to /app
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to /app
COPY . .

# Build the Angular app
RUN npm run build

# Expose port 4200 for the app to listen on
EXPOSE 4200

# Run the app when the container starts
CMD ["npm", "start"]
