version: '3'
services:
  backend:
    image: raqpha/express-app:latest
    container_name: express-app
    ports:
      - "3000:3000"
    restart: always
  frontend:
    image: raqpha/angular-app:latest
    container_name: angular-app
    ports:
      - "4200:4200"
    restart: always
